// src/components/cell-picker/CellPicker.tsx
import { useState, useRef, useEffect } from 'react'
import { createPortal } from 'react-dom'
import type { Staff, TimeBlock } from '@/types'
import { PALETTE, OFF_BLOCKS } from '@/lib/constants'
import { fmtT } from '@/lib/utils'
import { DirectTimeInput } from './DirectTimeInput'

interface Props {
  s: Staff
  globalTemplates: TimeBlock[]
  currentBlockId?: string | null
  onSelect: (block: TimeBlock | null) => void
  onSelectCustomTime: (inTime: string, outTime: string) => void
  onClose: () => void
}

function Block({ b, currentBlockId, onSelect }: { b: TimeBlock; currentBlockId?: string | null; onSelect: (b: TimeBlock) => void }) {
  const c = PALETTE[b.colorIdx]
  const sel = currentBlockId === b.id
  return (
    <div onClick={() => onSelect(b)} style={{
      background: sel ? c.bg : 'transparent', color: c.color,
      border: `1.5px ${sel ? 'solid' : 'dashed'} ${c.color}`,
      borderRadius: 7, padding: '6px 10px', cursor: 'pointer',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      fontSize: 11, fontWeight: 700, minWidth: 60, transition: 'all .1s',
    }}>
      <span>{b.label}</span>
      {b.inH != null && <>
        <span style={{ fontSize: 10, fontFamily: "'DM Sans',sans-serif", fontWeight: 600 }}>{fmtT(b.inH, b.inM)}</span>
        <span style={{ fontSize: 10, opacity: .7, fontFamily: "'DM Sans',sans-serif" }}>{fmtT(b.outH!, b.outM)}</span>
      </>}
    </div>
  )
}

export function CellPicker({ s, globalTemplates, currentBlockId, onSelect, onSelectCustomTime, onClose }: Props) {
  const [search, setSearch] = useState('')
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) onClose() }
    const k = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose() }
    document.addEventListener('mousedown', h)
    document.addEventListener('keydown', k)
    return () => { document.removeEventListener('mousedown', h); document.removeEventListener('keydown', k) }
  }, [onClose])

  const personalFiltered = search
    ? s.timeBlocks.filter(b => b.label.includes(search) || b.short.includes(search))
    : s.timeBlocks
  const globalFiltered = search
    ? globalTemplates.filter(b => b.label.includes(search) || b.short.includes(search))
    : globalTemplates

  return createPortal(
    <>
      <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,.4)', zIndex: 9998 }} />
      <div ref={ref} style={{
        position: 'fixed', top: '50%', left: '50%',
        transform: 'translate(-50%,-50%)',
        zIndex: 9999, background: '#fff',
        border: '1.5px solid #dde3ef', borderRadius: 12,
        boxShadow: '0 20px 60px rgba(15,32,68,.35)',
        padding: '20px',
        width: 'min(480px, 90vw)',
        maxHeight: '80vh', overflowY: 'auto',
      }}>
        <input
          value={search}
          onChange={e => setSearch(e.target.value)}
          placeholder="検索..."
          autoFocus
          style={{
            width: '100%', border: '1.5px solid #dde3ef', borderRadius: 6,
            padding: '4px 8px', fontSize: 11.5, outline: 'none', background: '#f8faff',
            marginBottom: 10, fontFamily: "'Noto Sans JP',sans-serif",
          }}
        />

        {/* Personal */}
        {personalFiltered.length > 0 && (
          <div style={{ marginBottom: 10 }}>
            <div style={{ fontSize: 11.5, fontWeight: 700, color: '#0f766e', marginBottom: 8, letterSpacing: '.02em' }}>👤 {s.name} の個人テンプレート</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
              {personalFiltered.map(b => <Block key={b.id} b={b} currentBlockId={currentBlockId} onSelect={onSelect} />)}
            </div>
          </div>
        )}

        {/* Global */}
        {globalFiltered.length > 0 && (
          <div style={{ marginBottom: 10 }}>
            <div style={{ fontSize: 11.5, fontWeight: 700, color: '#6d28d9', marginBottom: 8, letterSpacing: '.02em' }}>🌐 共通テンプレート</div>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, maxHeight: 100, overflowY: 'auto' }}>
              {globalFiltered.map(b => <Block key={b.id} b={b} currentBlockId={currentBlockId} onSelect={onSelect} />)}
            </div>
          </div>
        )}

        {/* Off blocks */}
        {!search && (
          <div style={{ marginBottom: 8 }}>
            <div style={{ fontSize: 9.5, fontWeight: 700, color: '#94a3b8', marginBottom: 5 }}>休日</div>
            <div style={{ display: 'flex', gap: 4 }}>
              {OFF_BLOCKS.map(b => {
                const c = PALETTE[b.colorIdx]
                const sel = currentBlockId === b.id
                return (
                  <div key={b.id} onClick={() => onSelect(b)} style={{
                    background: sel ? c.bg : 'transparent', color: c.color,
                    border: `1.5px ${sel ? 'solid' : 'dashed'} ${c.color}`,
                    borderRadius: 5, padding: '4px 10px', cursor: 'pointer',
                    fontSize: 11, fontWeight: 700,
                  }}>{b.label}</div>
                )
              })}
            </div>
          </div>
        )}

        {/* Direct time input */}
        {!search && <DirectTimeInput onApply={onSelectCustomTime} onClose={onClose} />}

        <div style={{ borderTop: '1px solid #f1f5f9', paddingTop: 6, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <button onClick={() => onSelect(null)} style={{ fontSize: 12, color: '#94a3b8', background: 'none', border: 'none', cursor: 'pointer' }}>✕ クリア</button>
          <button onClick={onClose} style={{ fontSize: 12, color: '#fff', background: '#0f2044', border: 'none', borderRadius: 6, padding: '4px 14px', cursor: 'pointer', fontFamily: "'Noto Sans JP',sans-serif" }}>閉じる</button>
        </div>
      </div>
    </>,
    document.body
  )
}

// src/components/grid/CellPicker.vue
<template>
  <Teleport to="body">
    <div
      class="fixed inset-0 bg-black/40 z-[9999] flex items-center justify-center p-4"
      @click.self="$emit('close')"
    >
      <div class="bg-brand-surface rounded-2xl shadow-2xl w-full max-w-sm max-h-[80vh] flex flex-col overflow-hidden border border-brand-border">
        <!-- ヘッダー -->
        <div class="flex items-center justify-between px-4 py-3 border-b border-brand-border">
          <div class="text-sm font-bold text-brand-text">{{ staff.name }} — {{ dateLabel }}</div>
          <button class="text-brand-muted hover:text-brand-text transition-colors" @click="$emit('close')">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
          </button>
        </div>

        <!-- 検索 -->
        <div class="px-3 pt-2">
          <input
            v-model="query"
            placeholder="ブロックを検索..."
            class="w-full text-xs bg-brand-surface2 border border-brand-border rounded-xl px-3 py-1.5 focus:outline-none focus:border-brand-accent transition-colors"
          />
        </div>

        <!-- ブロック一覧 -->
        <div class="overflow-y-auto flex-1 p-3 space-y-3">
          <!-- 個人テンプレート -->
          <div v-if="personalFiltered.length">
            <div class="text-[9px] font-bold text-brand-muted uppercase tracking-widest mb-1.5">個人テンプレート</div>
            <div class="flex flex-wrap gap-1.5">
              <BlockChip v-for="b in personalFiltered" :key="b.id" :block="b" :selected="effectiveBlockId === b.id" @click="selectBlock(b)" />
            </div>
          </div>

          <!-- 共通テンプレート -->
          <div v-if="globalFiltered.length">
            <div class="text-[9px] font-bold text-brand-muted uppercase tracking-widest mb-1.5">共通テンプレート</div>
            <div class="flex flex-wrap gap-1.5">
              <BlockChip v-for="b in globalFiltered" :key="b.id" :block="b" :selected="effectiveBlockId === b.id" @click="selectBlock(b)" />
            </div>
          </div>

          <!-- 休暇 -->
          <div v-if="offFiltered.length">
            <div class="text-[9px] font-bold text-brand-muted uppercase tracking-widest mb-1.5">休暇</div>
            <div class="flex flex-wrap gap-1.5">
              <BlockChip v-for="b in offFiltered" :key="b.id" :block="b" :selected="effectiveBlockId === b.id" @click="selectBlock(b)" />
            </div>
          </div>

          <!-- 直接入力 -->
          <DirectTimeInput @apply="applyTime" />
        </div>

        <!-- フッター -->
        <div class="px-3 py-2 border-t border-brand-border flex gap-2">
          <button
            class="flex-1 text-xs font-bold py-1.5 rounded-xl border border-brand-border text-brand-muted hover:bg-brand-surface2 transition-colors"
            @click="$emit('clear')"
          >クリア</button>
          <button
            class="text-xs font-bold py-1.5 px-4 rounded-xl border border-brand-border text-brand-muted hover:bg-brand-surface2 transition-colors"
            @click="$emit('close')"
          >閉じる</button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Staff, TimeBlock } from '@/types'
import { PALETTE } from '@/constants/palette'
import { OFF_BLOCKS } from '@/constants/offBlocks'
import { JP_WD } from '@/utils/dateHelpers'
import DirectTimeInput from './DirectTimeInput.vue'

const props = defineProps<{
  staff: Staff
  dateObj: Date
  globalTemplates: TimeBlock[]
  effectiveBlockId?: string
}>()

const emit = defineEmits<{
  select: [block: TimeBlock]
  clear: []
  close: []
  applyTime: [inTime: string, outTime: string]
}>()

const query = ref('')

const dateLabel = computed(() => {
  const d = props.dateObj
  return `${d.getMonth() + 1}/${d.getDate()}(${JP_WD[d.getDay()]})`
})

function filterBlocks(blocks: TimeBlock[]) {
  if (!query.value) return blocks
  const q = query.value.toLowerCase()
  return blocks.filter(b => b.label.toLowerCase().includes(q) || b.short.toLowerCase().includes(q))
}

const personalFiltered = computed(() => filterBlocks(props.staff.timeBlocks))
const globalFiltered = computed(() => filterBlocks(props.globalTemplates))
const offFiltered = computed(() => filterBlocks(OFF_BLOCKS))

function selectBlock(b: TimeBlock) {
  emit('select', b)
  emit('close')
}

function applyTime(inTime: string, outTime: string) {
  emit('applyTime', inTime, outTime)
  emit('close')
}
</script>

<script lang="ts">
// BlockChip インラインコンポーネント
import { defineComponent, h } from 'vue'
import { PALETTE as P } from '@/constants/palette'
import type { TimeBlock as TB } from '@/types'
import { fmtT } from '@/utils/dateHelpers'

const BlockChip = defineComponent({
  props: { block: Object as () => TB, selected: Boolean },
  emits: ['click'],
  setup(props, { emit }) {
    return () => {
      const b = props.block!
      const c = P[b.colorIdx]
      return h('button', {
        type: 'button',
        onClick: () => emit('click'),
        style: {
          background: c.bg,
          color: c.color,
          border: `2px solid ${props.selected ? c.color : 'transparent'}`,
          borderRadius: '8px',
          padding: '4px 8px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          minWidth: '48px',
          cursor: 'pointer',
          transition: 'all 0.1s',
        },
      }, [
        h('span', { style: { fontSize: '11px', fontWeight: 700 } }, b.short || b.label.slice(0, 3)),
        b.inH != null
          ? h('span', { style: { fontSize: '9px', fontFamily: 'JetBrains Mono, monospace' } }, fmtT(b.inH!, b.inM!))
          : null,
        b.outH != null
          ? h('span', { style: { fontSize: '9px', opacity: 0.75, fontFamily: 'JetBrains Mono, monospace' } }, fmtT(b.outH!, b.outM!))
          : null,
      ])
    }
  },
})

export { BlockChip }
</script>
