// src/components/grid/ShiftCell.vue
<template>
  <td
    class="border border-brand-border text-center align-middle relative select-none"
    :class="[
      isWeekly ? 'min-w-[90px] h-[52px]' : 'min-w-[36px] h-[42px]',
      isAfterLeave ? 'bg-brand-surface2 opacity-40' : 'bg-brand-surface',
      !locked && !isAfterLeave ? 'cursor-pointer hover:brightness-95' : '',
    ]"
    @click="openPicker"
  >
    <!-- セル内容 -->
    <template v-if="eff">
      <div
        v-if="!eff.isOff"
        class="flex flex-col items-center justify-center h-full px-0.5"
        :style="{ background: cellBg, color: cellColor }"
      >
        <span class="font-bold leading-none" :class="isWeekly ? 'text-[11px]' : 'text-[9px]'">{{ blockShort }}</span>
        <span v-if="isWeekly" class="font-mono leading-none text-[9px] mt-0.5">{{ eff.inTime }}</span>
        <span v-if="isWeekly" class="font-mono leading-none text-[9px] opacity-75">{{ eff.outTime }}</span>
      </div>
      <div
        v-else
        class="flex items-center justify-center h-full font-bold"
        :class="isWeekly ? 'text-[11px]' : 'text-[9px]'"
        :style="{ background: cellBg, color: cellColor }"
      >{{ blockShort }}</div>
    </template>
    <!-- 手動上書きインジケーター -->
    <div v-if="isManual" class="absolute top-0 right-0 w-1.5 h-1.5 bg-orange-400 rounded-bl" />

    <!-- ピッカー -->
    <CellPicker
      v-if="pickerOpen"
      :staff="staff"
      :dateObj="dateObj"
      :globalTemplates="globalTemplates"
      :effectiveBlockId="eff?.blockId"
      @select="onSelect"
      @clear="onClear"
      @close="pickerOpen = false"
      @applyTime="onApplyTime"
    />
  </td>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import type { Staff, TimeBlock } from '@/types'
import { useShiftStore } from '@/stores/useShiftStore'
import { getEffective, cellKey, findBlock } from '@/utils/shiftLogic'
import { PALETTE } from '@/constants/palette'
import { OFF_BLOCKS } from '@/constants/offBlocks'
import { fmtT } from '@/utils/dateHelpers'
import CellPicker from './CellPicker.vue'

const props = defineProps<{
  staff: Staff
  dateObj: Date
  globalTemplates: TimeBlock[]
  locked: boolean
  isWeekly: boolean
}>()

const shift = useShiftStore()
const pickerOpen = ref(false)

const key = computed(() => cellKey(props.staff.id, props.dateObj))

const isManual = computed(() => shift.cellData[key.value] !== undefined)

const eff = computed(() => getEffective(props.staff, props.dateObj, shift.cellData, props.globalTemplates))

const block = computed(() => {
  if (!eff.value?.blockId) return null
  return findBlock(eff.value.blockId, props.staff.timeBlocks, props.globalTemplates)
})

const blockShort = computed(() => block.value?.short ?? block.value?.label.slice(0, 3) ?? '')

const cellBg = computed(() => {
  if (!block.value) return 'transparent'
  return PALETTE[block.value.colorIdx].bg
})

const cellColor = computed(() => {
  if (!block.value) return 'inherit'
  return PALETTE[block.value.colorIdx].color
})

const isAfterLeave = computed(() => {
  if (!props.staff.leaveDate) return false
  const d = props.dateObj
  const dStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
  return dStr > props.staff.leaveDate
})

function openPicker() {
  if (props.locked || isAfterLeave.value) return
  pickerOpen.value = true
}

function onSelect(b: TimeBlock) {
  if (b.inH === null) {
    shift.setCellData(props.staff.id, props.dateObj, { blockId: b.id, isOff: true, inTime: '', outTime: '' })
  } else {
    shift.setCellData(props.staff.id, props.dateObj, {
      blockId: b.id, isOff: false,
      inTime: fmtT(b.inH, b.inM!),
      outTime: fmtT(b.outH!, b.outM!),
    })
  }
}

function onClear() {
  shift.clearCell(props.staff.id, props.dateObj)
  pickerOpen.value = false
}

function onApplyTime(inTime: string, outTime: string) {
  shift.setCellData(props.staff.id, props.dateObj, { blockId: '', isOff: false, inTime, outTime })
}
</script>

// src/components/grid/ShiftCell.tsx
import { useState } from 'react'
import type { Staff } from '@/types'
import { PALETTE } from '@/lib/constants'
import { isToday, fmtT, findBlock } from '@/lib/utils'
import { useShiftStore } from '@/store/useShiftStore'
import { CellPicker } from '@/components/cell-picker/CellPicker'

interface Props {
  s: Staff
  dateObj: Date
  mode?: 'week' | 'month'
}

export function ShiftCell({ s, dateObj, mode = 'month' }: Props) {
  const [pickerOpen, setPickerOpen] = useState(false)
  const { globalTemplates, getEffective, setCellEntry, clearCell } = useShiftStore()

  const leaveDate = s.leaveDate ? new Date(s.leaveDate) : null
  const isAfterLeave = leaveDate ? dateObj > leaveDate : false

  const eff = isAfterLeave ? null : getEffective(s, dateObj)
  const b = eff?.blockId ? findBlock(eff.blockId, s.timeBlocks, globalTemplates) : null
  const bc = b ? PALETTE[b.colorIdx] : null

  const isSun = dateObj.getDay() === 0
  const isSat = dateObj.getDay() === 6
  const tod = isToday(dateObj)
  const auto = eff?.auto

  const bg = isAfterLeave
    ? '#f1f5f9'
    : eff?.isOff
    ? bc?.bg
    : isSun ? '#fff5f5' : isSat ? '#f0f5ff' : '#fff'

  const W = mode === 'week' ? 80 : 52

  function handleSelect(block: typeof b) {
    if (!block) { clearCell(s.id, dateObj); return }
    if (block.inH === null) {
      setCellEntry(s.id, dateObj, { inTime: '', outTime: '', blockId: block.id, isOff: true })
    } else {
      setCellEntry(s.id, dateObj, {
        inTime: fmtT(block.inH, block.inM),
        outTime: fmtT(block.outH!, block.outM),
        blockId: block.id,
        isOff: false,
      })
    }
    setPickerOpen(false)
  }

  function handleSelectCustomTime(inTime: string, outTime: string) {
    setCellEntry(s.id, dateObj, { inTime, outTime, blockId: undefined, isOff: false })
    setPickerOpen(false)
  }

  return (
    <>
      <td
        onClick={isAfterLeave ? undefined : () => setPickerOpen(true)}
        style={{
          height: mode === 'week' ? 58 : 52,
          textAlign: 'center', cursor: isAfterLeave ? 'default' : 'pointer',
          padding: 2, background: bg,
          outline: tod && !isAfterLeave ? '2px solid #c9a84c' : 'none',
          outlineOffset: '-2px', verticalAlign: 'middle',
          border: '1px solid #e2e8f0', position: 'relative', userSelect: 'none',
          minWidth: W, width: W,
          opacity: isAfterLeave ? 0.35 : 1,
        }}
        onMouseEnter={isAfterLeave ? undefined : e => (e.currentTarget.style.filter = 'brightness(.92)')}
        onMouseLeave={isAfterLeave ? undefined : e => (e.currentTarget.style.filter = '')}
      >
        {isAfterLeave ? (
          <span style={{ color: '#cbd5e1', fontSize: 11 }}>－</span>
        ) : eff?.isOff ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <span style={{ fontSize: 11, fontWeight: 700, color: bc?.color }}>{b?.short}</span>
          </div>
        ) : eff ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 0, lineHeight: 1.45 }}>
            <span style={{ fontSize: 9.5, fontWeight: 700, color: '#0f766e', fontFamily: "'DM Sans',sans-serif" }}>{eff.inTime || '—'}</span>
            <span style={{ fontSize: 9.5, fontWeight: 700, color: '#dc2626', fontFamily: "'DM Sans',sans-serif" }}>{eff.outTime || '—'}</span>
          </div>
        ) : (
          <span style={{ color: '#e2e8f0', fontSize: 16 }}>+</span>
        )}
        {auto && eff && <span style={{ position: 'absolute', top: 2, right: 2, width: 4, height: 4, borderRadius: '50%', background: '#c9a84c' }} />}
        {bc && eff && <span style={{ position: 'absolute', bottom: 1, left: 0, right: 0, textAlign: 'center', fontSize: 7, color: bc.color, fontWeight: 700 }}>{b?.short}</span>}
      </td>

      {pickerOpen && (
        <CellPicker
          s={s}
          globalTemplates={globalTemplates}
          currentBlockId={eff?.blockId}
          onSelect={handleSelect}
          onSelectCustomTime={handleSelectCustomTime}
          onClose={() => setPickerOpen(false)}
        />
      )}
    </>
  )
}
