// src/components/summary/SummaryView.tsx
import { useMemo } from 'react'
import { useShiftStore } from '@/store/useShiftStore'
import { INIT_DEPTS, PALETTE } from '@/lib/constants'
import { getDays, calcH, calcNetH, fmtT } from '@/lib/utils'

export function SummaryView() {
  const { staff, globalTemplates, cellData, year, month, getEffective } = useShiftStore()

  const monthDates = useMemo(() =>
    Array.from({ length: getDays(year, month) }, (_, i) => new Date(year, month, i + 1)),
    [year, month]
  )

  const summary = useMemo(() => staff.map(s => {
    let totalH = 0, workDays = 0
    monthDates.forEach(d => {
      const eff = getEffective(s, d)
      if (!eff || eff.isOff) return
      if (eff.inTime && eff.outTime) {
        const [ih, im] = eff.inTime.split(':').map(Number)
        const [oh, om] = eff.outTime.split(':').map(Number)
        workDays++
        totalH += calcNetH(calcH(ih, im, oh, om))
      }
    })
    return { id: s.id, workDays, totalH: +totalH.toFixed(1) }
  }), [staff, cellData, globalTemplates, year, month])

  const staffByDept = useMemo(() =>
    INIT_DEPTS.map(d => ({
      ...d,
      members: staff.filter(s => s.deptId === d.id).sort((a, b) => a.no - b.no),
    })),
    [staff]
  )

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {staffByDept.map(dept => {
        if (dept.members.length === 0) return null
        const dc = PALETTE[dept.colorIdx]
        return (
          <div key={dept.id} style={{
            background: '#fff', borderRadius: 11, border: '1.5px solid #dde3ef',
            overflow: 'hidden', boxShadow: '0 2px 10px rgba(15,32,68,.06)',
            borderTop: `3px solid ${dc.color}`,
          }}>
            <div style={{ background: dc.bg, color: dc.color, padding: '10px 16px', fontWeight: 600, fontSize: 13 }}>
              {dept.label} — {year}年 {month + 1}月
            </div>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr>
                  <th style={{ background: '#f8faff', color: '#0f2044', padding: '8px 12px', fontWeight: 700, textAlign: 'left', borderBottom: '2px solid #dde3ef', minWidth: 140 }}>スタッフ</th>
                  <th style={{ background: '#f8faff', padding: '8px 10px', fontWeight: 700, textAlign: 'center', borderBottom: '2px solid #dde3ef', color: '#0f2044' }}>出勤日数</th>
                  <th style={{ background: '#f8faff', padding: '8px 10px', fontWeight: 700, textAlign: 'center', borderBottom: '2px solid #dde3ef', color: '#0f2044' }}>総時間</th>
                  <th style={{ background: '#f8faff', padding: '8px 10px', fontWeight: 600, textAlign: 'left', borderBottom: '2px solid #dde3ef', color: '#64748b', fontSize: 11 }}>個人テンプレート</th>
                </tr>
              </thead>
              <tbody>
                {dept.members.map((s, ri) => {
                  const sm = summary.find(x => x.id === s.id)
                  if (!sm) return null
                  return (
                    <tr key={s.id} style={{ background: ri % 2 === 0 ? '#fff' : '#fafbff' }}>
                      <td style={{ padding: '8px 12px', borderBottom: '1px solid #e2e8f0', fontWeight: 600 }}>
                        <span style={{ color: '#94a3b8', fontSize: 10, marginRight: 6 }}>{s.no}</span>{s.name}
                      </td>
                      <td style={{ padding: '8px 10px', borderBottom: '1px solid #e2e8f0', textAlign: 'center' }}>
                        <span style={{ background: '#e8ecf5', color: '#0f2044', padding: '2px 9px', borderRadius: 8, fontFamily: "'DM Sans',sans-serif", fontWeight: 700, fontSize: 12 }}>{sm.workDays}日</span>
                      </td>
                      <td style={{ padding: '8px 10px', borderBottom: '1px solid #e2e8f0', textAlign: 'center' }}>
                        <span style={{ background: '#0f2044', color: '#c9a84c', padding: '2px 9px', borderRadius: 8, fontFamily: "'DM Sans',sans-serif", fontWeight: 700, fontSize: 12 }}>{sm.totalH}h</span>
                      </td>
                      <td style={{ padding: '8px 10px', borderBottom: '1px solid #e2e8f0' }}>
                        <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                          {s.timeBlocks.map(b => {
                            const c = PALETTE[b.colorIdx]
                            return (
                              <span key={b.id} style={{ background: c.bg, color: c.color, border: `1px solid ${c.color}`, padding: '1px 7px', borderRadius: 5, fontSize: 10, fontWeight: 700 }}>
                                {b.short} {b.inH != null ? `${fmtT(b.inH, b.inM)}-${fmtT(b.outH!, b.outM)}` : ''}
                              </span>
                            )
                          })}
                          {s.timeBlocks.length === 0 && <span style={{ fontSize: 10.5, color: '#e2e8f0' }}>—</span>}
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        )
      })}
    </div>
  )
}

// src/components/summary/SummaryView.vue
<template>
  <div class="flex-1 overflow-y-auto p-4">
    <div class="text-sm font-bold text-brand-text mb-3">{{ ui.monthLabel }} 集計</div>

    <template v-for="dept in deptSummaries" :key="dept.id">
      <div class="text-[10px] font-bold uppercase tracking-widest mb-2 px-1" :style="{ color: PALETTE[dept.colorIdx].color }">
        ── {{ dept.label }} ──
      </div>
      <div class="overflow-x-auto mb-4">
        <table class="text-xs w-full border-collapse">
          <thead>
            <tr>
              <th class="border border-brand-border bg-brand-surface2 px-2 py-1 text-left font-bold text-brand-muted">名前</th>
              <th class="border border-brand-border bg-brand-surface2 px-2 py-1 text-center font-bold text-brand-muted w-14">勤務日数</th>
              <th class="border border-brand-border bg-brand-surface2 px-2 py-1 text-center font-bold text-brand-muted w-14">総時間</th>
              <th class="border border-brand-border bg-brand-surface2 px-2 py-1 text-center font-bold text-brand-muted w-16">実働(控除)</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in dept.rows" :key="row.id" class="hover:bg-brand-surface2 transition-colors">
              <td class="border border-brand-border px-2 py-1 font-medium text-brand-text">{{ row.name }}</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ row.workDays }}</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ row.totalH }}h</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ row.netH }}h</td>
            </tr>
            <tr class="bg-brand-surface2 font-bold">
              <td class="border border-brand-border px-2 py-1 text-brand-muted">合計</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ dept.totalDays }}</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ dept.totalH }}h</td>
              <td class="border border-brand-border px-2 py-1 text-center font-mono text-brand-text">{{ dept.totalNetH }}h</td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useUIStore } from '@/stores/useUIStore'
import { useStaffStore } from '@/stores/useStaffStore'
import { useTemplateStore } from '@/stores/useTemplateStore'
import { useShiftStore } from '@/stores/useShiftStore'
import { PALETTE } from '@/constants/palette'
import { getEffective, calcNetH } from '@/utils/shiftLogic'

const ui = useUIStore()
const staffStore = useStaffStore()
const templateStore = useTemplateStore()
const shift = useShiftStore()

const deptSummaries = computed(() => {
  const dates = ui.monthDates

  return staffStore.depts.map(dept => {
    const members = staffStore.staffByDept(ui.showInactive, ui.year, ui.month)
      .find(d => d.id === dept.id)?.members ?? []

    const rows = members.map(s => {
      let workDays = 0
      let totalH = 0
      let netH = 0

      for (const d of dates) {
        const eff = getEffective(s, d, shift.cellData, templateStore.globalTemplates)
        if (!eff || eff.isOff) continue
        if (!eff.inTime || !eff.outTime) continue

        workDays++
        const [ih, im] = eff.inTime.split(':').map(Number)
        const [oh, om] = eff.outTime.split(':').map(Number)

        const raw = (oh * 60 + om - (ih * 60 + im) + 1440) % 1440 / 60
        totalH += raw
        netH += calcNetH(ih, im, oh, om)
      }

      return {
        id: s.id,
        name: s.name,
        workDays,
        totalH: +totalH.toFixed(1),
        netH: +netH.toFixed(1),
      }
    })

    return {
      ...dept,
      rows,
      totalDays: rows.reduce((s, r) => s + r.workDays, 0),
      totalH: +rows.reduce((s, r) => s + r.totalH, 0).toFixed(1),
      totalNetH: +rows.reduce((s, r) => s + r.netH, 0).toFixed(1),
    }
  })
})
</script>
